(() => {
  const locales = { fr: {
    badge: "Scénario synthétique — exécution réelle du CGE", technical: "Mode technique", presentation: "Mode présentation", next: "Point suivant", previous: "Point précédent", pause: "Pause", resume: "Reprendre", reset: "Reset", proof: "Voir la preuve", local: "Local uniquement", noAuthority: "Aucune autorité de sécurité", synthetic: "Les événements sont synthétiques ; les résultats viennent du moteur.", chapters: ["Le problème", "Contexte", "Mémoire", "Ambiguïté", "Déviation", "Adaptation", "Replay", "Local-first", "Différenciation", "État réel"], warmup: "Warm-up", observations: "observations", chains: "chaînes", hypotheses: "hypothèses", routines: "routines", journal: "séquence WAL", continuity: "continuité du journal", explained: "Déviation explicable", structure: "Structure", temporal: "Temporalité", interval: "Intervalle", complete: "Complète", partial: "Partielle", measured: "mesuré", noDecision: "Aucune alternative sélectionnée automatiquement", historical: "Historique", current: "Occurrence actuelle", proven: "Prouvé aujourd’hui", toProve: "À prouver sur le terrain", limitation: "Limite à mentionner", localMessage: "Aucun cloud requis pour l’apprentissage", before: "avant", after: "après", equal: "État avant redémarrage == état après replay", evidence: "Preuve", status: "Statut", view: "Vue", data: "Données réelles du moteur" },
  en: { badge: "Synthetic scenario — real CGE execution", technical: "Technical mode", presentation: "Presenter mode", next: "Next point", previous: "Previous point", pause: "Pause", resume: "Resume", reset: "Reset", proof: "View evidence", local: "Local only", noAuthority: "No security authority", synthetic: "Events are synthetic; results come from the engine.", chapters: ["The problem", "Context", "Memory", "Ambiguity", "Deviation", "Adaptation", "Replay", "Local-first", "Differentiation", "Real status"], warmup: "Warm-up", observations: "observations", chains: "chains", hypotheses: "hypotheses", routines: "routines", journal: "WAL sequence", continuity: "journal continuity", explained: "Explainable deviation", structure: "Structure", temporal: "Temporal", interval: "Interval", complete: "Complete", partial: "Partial", measured: "measured", noDecision: "No alternative selected automatically", historical: "History", current: "Current occurrence", proven: "Proven today", toProve: "To prove in the field", limitation: "Limitation to mention", localMessage: "No cloud required for learning", before: "before", after: "after", equal: "State before restart == state after replay", evidence: "Evidence", status: "Status", view: "View", data: "Actual engine data" }
  };
  const t = locales[window.SYNORA_LOCALE === "en" ? "en" : "fr"];
  let data = null, chapter = 0, paused = false, technical = !!window.SYNORA_TECHNICAL, eventIndex = 0, startedAt = Date.now();
  const app = document.getElementById("app");
  const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const fmt = (value) => value ? new Date(value).toLocaleString(window.SYNORA_LOCALE === "en" ? "en-GB" : "fr-FR", {dateStyle:"short", timeStyle:"short"}) : "—";
  const num = (value) => Number(value || 0).toLocaleString(window.SYNORA_LOCALE === "en" ? "en-GB" : "fr-FR");
  const chapterEvents = (name) => (data?.events || []).filter((e) => e.chapter === name);
  const latest = (name) => { const list = chapterEvents(name); return list[list.length - 1] || {}; };
  const metrics = () => { const s = data.snapshot || {}; return `<div class="grid-cards"><div class="metric"><b>${num(s.observation_count)}</b><span>${t.observations}</span></div><div class="metric"><b>${num(s.chain_count)}</b><span>${t.chains}</span></div><div class="metric"><b>${num(s.hypothesis_count)}</b><span>${t.hypotheses}</span></div><div class="metric"><b>${num(s.routine_count)}</b><span>${t.routines}</span></div></div>`; };
  const shell = (body) => `<div class="shell"><header class="topbar"><div class="brand"><div class="mark">S</div><div><span class="eyebrow">Cognitive Graph Engine</span><strong>Synora</strong><small>${t.badge}</small></div></div><div class="top-actions"><button class="button" id="proof">${t.proof}</button><button class="button ${!technical ? "active" : ""}" id="presentation">${t.presentation}</button><button class="button ${technical ? "active" : ""}" id="technical">${t.technical}</button><button class="button" id="reset">${t.reset}</button></div></header><section class="content">${body}</section><footer class="footer"><span><strong>${t.noAuthority}</strong> · ${t.synthetic}</span><span id="presenter-timer">00:00</span><span>Seed ${esc(data.seed)} · ${esc(data.scenario)}</span></footer></div>`;
  const nav = () => `<nav class="chapter-nav" aria-label="Chapters">${t.chapters.map((label, i) => `<button data-chapter="${i}" class="${i === chapter ? "active" : ""}">${i + 1} · ${label}</button>`).join("")}</nav>`;
  const controls = () => `<div class="controls"><button class="button" id="prev" ${chapter === 0 ? "disabled" : ""}>← ${t.previous}</button><button class="button primary" id="pause">${paused ? t.resume : t.pause}</button><button class="button" id="next" ${chapter === t.chapters.length - 1 ? "disabled" : ""}>${t.next} →</button></div>`;
  function render() {
    if (!data) { app.innerHTML = `<div class="loading">${t.synthetic}</div>`; return; }
    const screens = [problem, context, memory, ambiguity, deviation, adaptation, replay, privacy, differentiation, truth];
    app.innerHTML = shell(`${nav()}${screens[chapter]()}${controls()}`);
    document.querySelectorAll("[data-chapter]").forEach((button) => button.onclick = () => { chapter = Number(button.dataset.chapter); render(); });
    document.getElementById("next").onclick = () => { if (!paused) { chapter = Math.min(9, chapter + 1); render(); } };
    document.getElementById("prev").onclick = () => { chapter = Math.max(0, chapter - 1); render(); };
    document.getElementById("pause").onclick = () => { paused = !paused; render(); };
    document.getElementById("presentation").onclick = () => { technical = false; render(); };
    document.getElementById("technical").onclick = () => { technical = true; render(); };
    document.getElementById("reset").onclick = reset;
    document.getElementById("proof").onclick = () => alert(proofText(["local-first", "local-first", "routine-learning", "ambiguity-preservation", "pre-learning-deviation", "continuous-adaptation", "deterministic-replay", "local-first", "transactional-durability", "security-authority"][chapter]));
    document.querySelectorAll("[data-proof]").forEach((button) => button.onclick = () => alert(proofText(button.dataset.proof)));
    updateTimer();
  }
  function header(kicker, title, text) { return `<div class="hero-copy"><span class="eyebrow">${esc(kicker)}</span><h2>${esc(title)}</h2><p class="lead">${esc(text)}</p>${metrics()}</div>`; }
  function problem() { return `<div class="hero">${header(t.chapters[0], window.SYNORA_LOCALE === "en" ? "From reaction to measurable local memory" : "De la réaction à la mémoire locale mesurable", window.SYNORA_LOCALE === "en" ? "Traditional home systems react to an event. The CGE compares it with the memory available in this home." : "Les systèmes domotiques traditionnels réagissent à un événement. Le CGE le compare à la mémoire disponible dans ce domicile.") }<div class="visual"><div class="compare"><div><strong>Illustration conceptuelle · système à règles</strong><p>Mouvement détecté à 23 h 42</p></div><div><strong>CGE</strong><p>Quelle chaîne candidate ? Où, quand, dans quel contexte ?</p></div></div><div class="notice">${t.noAuthority}</div></div></div>`; }
  function context() { const item = latest("context") || latest("memory"); return `<div class="hero">${header(t.chapters[1], window.SYNORA_LOCALE === "en" ? "An event becomes a context frame" : "Un événement devient un contexte", "Le CGE ne traite pas seulement ce qui s’est passé, mais où, quand et dans quel contexte cela s’est produit.")}<div class="visual"><div class="flow"><span class="node active">événement brut<br><small>${esc(item.payload?.observation_id || "demo")}</small></span><span class="arrow">→</span><span class="node active">frame contextuel<br><small>${esc(item.payload?.node_id || "zone domestique")}</small></span><span class="arrow">→</span><span class="node active">observation cognitive</span></div><div class="house"><div class="room bedroom">Chambre</div><div class="room entrance">Entrée</div><div class="room hallway">Couloir</div><div class="room kitchen">Cuisine</div><div class="room living">Séjour</div><div class="path"></div></div></div></div>`; }
  function memory() { const list = chapterEvents("memory"); return `<div class="hero">${header(t.chapters[2], window.SYNORA_LOCALE === "en" ? "Memory is built, not assumed" : "Une mémoire se construit", "Le domicile ne reçoit pas un modèle générique. Il construit localement son propre historique comportemental.")}<div class="visual"><div class="timeline">${list.slice(0, 18).map((e, i) => `<span class="bar" style="--height:${25 + ((i * 17) % 70)}%" title="${esc(e.payload?.observation_id)}"></span>`).join("")}</div><p class="small">${num(list.length)} événements observés · premières répétitions · évaluation après warm-up</p><div class="house"><div class="room entrance">Entrée</div><div class="room hallway">Couloir</div><div class="room kitchen">Cuisine</div><div class="path"></div></div></div></div>`; }
  function ambiguity() { const item = latest("ambiguity"); const h = data.snapshot.hypotheses || []; return `<div class="hero">${header(t.chapters[3], window.SYNORA_LOCALE === "en" ? "Uncertainty stays visible" : "L’ambiguïté reste visible", "Le CGE sait dire « je ne sais pas encore ».")}<div class="visual"><div class="tree">Observation <span class="branch">${esc(item.payload?.observation_id || "ambiguous")}</span><br>├── <span class="branch">Hypothèse A · chaîne candidate</span><br>└── <span class="branch">Hypothèse B · chaîne candidate</span></div><div class="notice">${t.noDecision}</div>${technical ? techHypotheses(h) : ""}</div></div>`; }
  function deviation() { const item = latest("deviation"), d = item.payload?.deviation || data.snapshot.latest_deviation || {}; const factor = (name, value, color) => `<div class="factor"><span>${name}</span><i style="--value:${Math.max(3, Math.min(100, Number(value || 0) / 10))}%;background:${color}"></i><b>${num(value)}</b></div>`; return `<div class="hero">${header(t.chapters[4], window.SYNORA_LOCALE === "en" ? "A measured divergence" : "Une divergence mesurée", "The CGE measures a decomposable difference with memory; it does not infer its cause.")}<div class="visual"><div class="compare"><div><strong>${t.historical}</strong><p>Entrée → couloir → cuisine<br>habituellement en soirée</p></div><div><strong>${t.current}</strong><p>Entrée → couloir<br>à 02 h 15 · mode night</p></div></div><div class="panel" style="margin-top:12px"><h3>${t.explained} · score ${num(d.score)} / 1000 · couverture ${num(d.coverage)} / 1000</h3>${factor(t.structure, d.factors?.[0]?.score, "var(--blue)")}${factor(t.temporal, d.factors?.[1]?.score, "var(--amber)")}${factor(t.interval, d.factors?.[2]?.score, "var(--orange)")}</div>${technical ? `<p class="mono">status=${esc(d.status)} band=${esc(d.band)} fingerprint=${esc(d.fingerprint)}</p>` : ""}</div></div>`; }
  function adaptation() { const list = chapterEvents("adaptation"); const routines = data.snapshot.routines || []; return `<div class="hero">${header(t.chapters[5], window.SYNORA_LOCALE === "en" ? "A new pattern becomes memory" : "Un nouveau motif devient mémoire", "Le CGE ne fige pas une maison dans son passé. Il continue d’apprendre les occurrences observées.")}<div class="visual"><div class="timeline">${list.slice(0, 18).map((e, i) => `<span class="bar shift" style="--height:${30 + ((i * 13) % 65)}%"></span>`).join("")}</div><p class="small">Nouvelle plage horaire · score initial plus élevé · distribution enrichie · divergence progressivement réduite</p><div class="notice">L’adaptation est descriptive et doit encore être calibrée sur des données domestiques réelles.</div>${technical ? `<p class="mono">routines=${num(routines.length)} · occurrences=${num(routines.reduce((n, r) => n + Number(r.OccurrenceCount || 0), 0))}</p>` : ""}</div></div>`; }
  function replay() { const events = data.events.filter((e) => e.kind === "replay.completed"); const p = events[events.length - 1]?.payload || {}; return `<div class="hero">${header(t.chapters[6], window.SYNORA_LOCALE === "en" ? "Durable memory survives restart" : "La mémoire durable survit au redémarrage", "La mémoire cognitive n’est pas un état volatile. Elle est versionnée, vérifiable et rejouable.")}<div class="visual"><div class="compare"><div><strong>${t.before}</strong><p class="mono">${esc(p.before || data.snapshot.durable_digest)}</p></div><div><strong>${t.after}</strong><p class="mono">${esc(p.after || data.snapshot.replay_digest || data.snapshot.durable_digest)}</p></div></div><div class="notice">${p.equal !== false ? "✓ " : "✕ "}${t.equal}</div><p class="small">${t.continuity} · store éphémère de déviation vidé conformément à sa conception.</p>${technical ? `<p class="mono">${esc(JSON.stringify(data.snapshot.performance || {}))}</p>` : ""}</div></div>`; }
  function privacy() { return `<div class="hero">${header(t.chapters[7], window.SYNORA_LOCALE === "en" ? "Local-first by construction" : "Local-first par construction", "Le calcul, le stockage et le journal du CGE démontré restent dans la centrale Synora.")}<div class="visual"><div class="flow"><span class="node">Caméras et capteurs</span><span class="arrow">→</span><span class="node">Centrale Synora</span><span class="arrow">→</span><span class="node active">CGE local</span></div><div class="notice">${t.localMessage}</div><p class="small">Pseudonymisation de l’essai terrain · absence d’image et d’embedding dans la télémétrie · exports anonymisés.</p></div></div>`; }
  function differentiation() { const items = ["Graphe cognitif contextualisé","Hypothèses concurrentes","Mémoire versionnée","Routines locales","Déviation pré-apprentissage","Apprentissage continu","Explicabilité","Résilience transactionnelle","Privacy by design","Autorité graduée"]; return `<div class="panel"><span class="eyebrow">${t.chapters[8]}</span><h2>Pourquoi le CGE est difficile à reproduire</h2><div class="grid-cards">${items.map((item, i) => `<div class="metric"><b>${i + 1}</b><span>${item}</span></div>`).join("")}</div><p class="kicker">Les événements sont reliés dans le temps, l’espace et le contexte domestique ; les mutations sont historisées ; les scores sont décomposables ; la sécurité reste hors de cette frontière.</p></div>`; }
  function truth() { const claims = demoClaims(); const qualification = data.manifest?.qualification_available ? "" : `<p><span class="status warn">Qualification non chargée</span></p>`; return `<div class="panel"><span class="eyebrow">${t.chapters[9]}</span><h2>Ce qui est prouvé / ce qui reste à prouver</h2><div class="section-grid"><div><h3>${t.proven}</h3><p>Cycle cognitif · durabilité · replay · routine learning · déviation explicable · isolation · campagnes synthétiques · instrumentation terrain.</p></div><div><h3>${t.toProve}</h3><p>Calibration sur un vrai domicile · séparation des variations légitimes · vitesse optimale d’adaptation · capteurs physiques · croissance sur plusieurs mois · valeur opérationnelle pour la sécurité.</p></div></div>${qualification}<div class="notice">synthetic_episode_not_separated · La mécanique cognitive est fonctionnelle et qualifiée. La calibration comportementale doit maintenant être validée sur le terrain.</div>${technical ? `<div class="table-wrap" style="margin-top:18px"><table class="tech-table"><thead><tr><th>${t.view}</th><th>${t.status}</th><th>${t.evidence}</th></tr></thead><tbody>${claims.map((c) => `<tr><td>${esc(c.title)}<br><span class="mono">${esc(c.id)}</span></td><td><span class="status ${c.status === "future" ? "future" : "good"}">${esc(c.status)}</span></td><td>${esc((c.evidence || []).join(" · "))}</td></tr>`).join("")}</tbody></table></div>` : ""}</div>`; }
  function techHypotheses(values) { return `<div class="table-wrap" style="margin-top:15px"><table class="tech-table"><thead><tr><th>ID</th><th>Family</th><th>Status</th><th>Revision</th></tr></thead><tbody>${(values || []).map((h) => `<tr><td class="mono">${esc(h.ID)}</td><td>${esc(h.Family)}</td><td>${esc(h.Status)}</td><td>${esc(h.Revision)}</td></tr>`).join("")}</tbody></table></div>`; }
  let claimsCache = [];
  function demoClaims() { return claimsCache; }
  function proofText(id) { const claim = claimsCache.find((x) => x.id === id); return claim ? `${claim.title}\n\n${claim.status}\n\n${(claim.evidence || []).join("\n")}\n\n${t.limitation}: ${(claim.limitations || []).join(" ")}` : t.synthetic; }
  async function load() {
    const embedded = document.getElementById("embedded-data")?.textContent.trim();
    try { data = embedded && embedded !== "__SYNORA_EMBEDDED_DATA__" && embedded !== "{}" ? JSON.parse(embedded) : await (await fetch("/api/scenario")).json(); } catch (_) { data = JSON.parse(embedded || "{}"); }
    const embeddedClaims = document.getElementById("embedded-claims")?.textContent.trim();
    try { claimsCache = embeddedClaims && embeddedClaims !== "__SYNORA_EMBEDDED_CLAIMS__" && embeddedClaims !== "{}" ? JSON.parse(embeddedClaims) : await (await fetch(window.location.protocol === "file:" ? "claims.json" : "/api/claims")).json(); claimsCache = claimsCache.claims || []; } catch (_) { claimsCache = []; }
    render();
  }
  async function reset() { try { const response = await fetch("/api/reset", {method:"POST"}); if (response.ok) data = await response.json(); } catch (_) { /* static export remains deterministic */ } startedAt = Date.now(); chapter = 0; render(); }
  function updateTimer() { const target = document.getElementById("presenter-timer"); if (!target) return; const elapsed = Math.floor((Date.now() - startedAt) / 1000); target.textContent = `${String(Math.floor(elapsed / 60)).padStart(2, "0")}:${String(elapsed % 60).padStart(2, "0")}`; }
  setInterval(updateTimer, 1000);
  // Ten stable chapters over nine minutes in Presenter mode. Technical mode
  // remains manually navigable for questions.
  setInterval(() => { if (data && !paused && !technical && !document.hidden && chapter < 9) { chapter += 1; render(); } }, 54000);
  document.addEventListener("keydown", (event) => { if (event.key === "ArrowRight") document.getElementById("next")?.click(); if (event.key === "ArrowLeft") document.getElementById("prev")?.click(); if (event.key === " ") { event.preventDefault(); document.getElementById("pause")?.click(); } if (event.key.toLowerCase() === "t") { technical = !technical; render(); } if (event.key.toLowerCase() === "r") reset(); if (event.key.toLowerCase() === "f") document.documentElement.requestFullscreen?.(); if (/^[1-9]$/.test(event.key)) { chapter = Number(event.key) - 1; render(); } });
  load();
})();
