package durableworkflow

import "errors"

var (
	ErrInvalidPolicy            = errors.New("durableworkflow: invalid policy")
	ErrInvalidWorkflowState     = errors.New("durableworkflow: invalid workflow state")
	ErrInvalidLayer             = errors.New("durableworkflow: invalid layer")
	ErrInvalidMutation          = errors.New("durableworkflow: invalid mutation")
	ErrInvalidTransaction       = errors.New("durableworkflow: invalid transaction")
	ErrInvalidLineage           = errors.New("durableworkflow: invalid lineage")
	ErrLayerStale               = errors.New("durableworkflow: layer stale")
	ErrLayerFingerprintMismatch = errors.New("durableworkflow: layer fingerprint mismatch")
	ErrFingerprintMismatch      = errors.New("durableworkflow: fingerprint mismatch")
	ErrMissingUpstreamLayer     = errors.New("durableworkflow: missing upstream layer")
	ErrSourceRevisionConflict   = errors.New("durableworkflow: source revision conflict")
	ErrSourceDigestConflict     = errors.New("durableworkflow: source digest conflict")
	ErrTransactionIDCollision   = errors.New("durableworkflow: transaction ID collision")
	ErrSequenceGap              = errors.New("durableworkflow: sequence gap")
	ErrSequenceRegression       = errors.New("durableworkflow: sequence regression")
	ErrRecordTooLarge           = errors.New("durableworkflow: record too large")
	ErrCheckpointTooLarge       = errors.New("durableworkflow: checkpoint too large")
	ErrChecksumMismatch         = errors.New("durableworkflow: checksum mismatch")
	ErrTruncatedRecord          = errors.New("durableworkflow: truncated record")
	ErrMidLogCorruption         = errors.New("durableworkflow: mid-log corruption")
	ErrInvalidGenesis           = errors.New("durableworkflow: invalid genesis")
	ErrSchemaMismatch           = errors.New("durableworkflow: schema mismatch")
	ErrPolicyMismatch           = errors.New("durableworkflow: policy mismatch")
	ErrCheckpointCorrupt        = errors.New("durableworkflow: checkpoint corrupt")
	ErrReplayMismatch           = errors.New("durableworkflow: replay mismatch")
	ErrStoreClosed              = errors.New("durableworkflow: store closed")
	ErrCommitNotDurable         = errors.New("durableworkflow: commit not durable")
	ErrInvalidFileMode          = errors.New("durableworkflow: invalid file mode")
	ErrInvalidRecord            = errors.New("durableworkflow: invalid record")
)
