package authorizationboundary

import "errors"

var (
	ErrInvalidPolicy                = errors.New("authorizationboundary: invalid policy")
	ErrInvalidAuthorizationContext  = errors.New("authorizationboundary: invalid authorization context")
	ErrInvalidPurpose               = errors.New("authorizationboundary: invalid purpose")
	ErrInvalidScope                 = errors.New("authorizationboundary: invalid scope")
	ErrInvalidPolicySet             = errors.New("authorizationboundary: invalid policy set")
	ErrInvalidRule                  = errors.New("authorizationboundary: invalid rule")
	ErrInvalidEffect                = errors.New("authorizationboundary: invalid effect")
	ErrRuleLimitReached             = errors.New("authorizationboundary: rule limit reached")
	ErrInvalidGrant                 = errors.New("authorizationboundary: invalid grant")
	ErrGrantLimitReached            = errors.New("authorizationboundary: grant limit reached")
	ErrScopeLimitReached            = errors.New("authorizationboundary: scope limit reached")
	ErrReasonLimitReached           = errors.New("authorizationboundary: reason limit reached")
	ErrGrantExpired                 = errors.New("authorizationboundary: grant expired")
	ErrGrantRevoked                 = errors.New("authorizationboundary: grant revoked")
	ErrGrantNotYetValid             = errors.New("authorizationboundary: grant not yet valid")
	ErrInvalidGrantSnapshot         = errors.New("authorizationboundary: invalid grant snapshot")
	ErrInvalidMappingAssessment     = errors.New("authorizationboundary: invalid mapping assessment")
	ErrMappingUnavailable           = errors.New("authorizationboundary: mapping unavailable")
	ErrRequestObsolete              = errors.New("authorizationboundary: request obsolete")
	ErrMissingSourceFingerprint     = errors.New("authorizationboundary: missing source fingerprint")
	ErrFingerprintMismatch          = errors.New("authorizationboundary: fingerprint mismatch")
	ErrPolicyConflict               = errors.New("authorizationboundary: policy conflict")
	ErrEligibilityDenied            = errors.New("authorizationboundary: eligibility denied")
	ErrExternalConfirmationRequired = errors.New("authorizationboundary: external confirmation required")
	ErrSourceRevisionConflict       = errors.New("authorizationboundary: source revision conflict")
	ErrInvalidAssessment            = errors.New("authorizationboundary: invalid assessment")
	ErrInvalidPlan                  = errors.New("authorizationboundary: invalid plan")
	ErrInvalidExplanation           = errors.New("authorizationboundary: invalid explanation")
	ErrContextExpired               = errors.New("authorizationboundary: context expired")
	ErrConflictLimitReached         = errors.New("authorizationboundary: conflict limit reached")
)
