// Command cge-contractgen generates and verifies the executable CGE contract
// registry. It never writes runtime configuration or durable CGE data.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"synora/internal/cge/contractcatalog"
	"synora/internal/cge/contractcatalog/gosurface"
)

const generatedPath = "internal/cge/contractcatalog/generated_registry.go"

func main() {
	if len(os.Args) != 2 || (os.Args[1] != "generate" && os.Args[1] != "check") {
		fmt.Fprintln(os.Stderr, "usage: cge-contractgen generate|check")
		os.Exit(2)
	}
	root, err := os.Getwd()
	if err != nil {
		fatal(err)
	}
	set, err := contractcatalog.Validate(root)
	if err != nil {
		fatal(err)
	}
	infos, err := gosurface.Scan(root, filepath.Join(root, "configs/cge/contracts/go-surfaces.yaml"))
	if err != nil {
		fatal(err)
	}
	implemented := make(map[string]bool, len(infos))
	for _, info := range infos {
		implemented[info.Package+"/"+info.Name] = true
	}
	for _, contract := range set.Catalog.Contracts {
		if contract.Implementation.Kind == "external" {
			continue
		}
		key := contract.Implementation.Package + "/" + contract.Implementation.Type
		if !implemented[key] {
			fatal(fmt.Errorf("contract %s implementation %s is not in the monitored Go surface", contract.ID, key))
		}
	}
	data, err := render(set)
	if err != nil {
		fatal(err)
	}
	target := filepath.Join(root, generatedPath)
	if os.Args[1] == "check" {
		current, err := os.ReadFile(target)
		if err != nil {
			fatal(fmt.Errorf("%s: %w", generatedPath, err))
		}
		if string(current) != string(data) {
			fatal(fmt.Errorf("%s: %s", generatedPath, contractcatalog.ErrGeneratedRegistryStale))
		}
		return
	}
	if err := os.WriteFile(target, data, 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) { fmt.Fprintln(os.Stderr, err); os.Exit(1) }

type canonicalSet struct {
	Catalog    contractcatalog.CatalogFile
	Boundaries contractcatalog.BoundariesFile
	Stores     contractcatalog.StoresFile
	Errors     contractcatalog.ErrorsFile
}

func render(set contractcatalog.CatalogSet) ([]byte, error) {
	contracts := append([]contractcatalog.CatalogContract(nil), set.Catalog.Contracts...)
	sort.Slice(contracts, func(i, j int) bool { return contracts[i].ID < contracts[j].ID })
	boundaries := append([]contractcatalog.CatalogBoundary(nil), set.Boundaries.Boundaries...)
	sort.Slice(boundaries, func(i, j int) bool { return boundaries[i].ID < boundaries[j].ID })
	stores := append([]contractcatalog.CatalogStore(nil), set.Stores.Stores...)
	sort.Slice(stores, func(i, j int) bool { return stores[i].ID < stores[j].ID })
	errors := append([]contractcatalog.CatalogError(nil), set.Errors.Errors...)
	sort.Slice(errors, func(i, j int) bool { return errors[i].ID < errors[j].ID })
	canonical := canonicalSet{Catalog: set.Catalog, Boundaries: set.Boundaries, Stores: set.Stores, Errors: set.Errors}
	canonical.Catalog.Contracts = contracts
	canonical.Boundaries.Boundaries = boundaries
	canonical.Stores.Stores = stores
	canonical.Errors.Errors = errors
	canonicalBytes, err := json.Marshal(canonical)
	if err != nil {
		return nil, err
	}
	global := sha256.Sum256(canonicalBytes)

	var b strings.Builder
	b.WriteString("// Code generated by cge-contractgen. DO NOT EDIT.\n\npackage contractcatalog\n\n")
	fmt.Fprintf(&b, "var generatedRegistry = Registry{\n\tCatalogFingerprint: %q,\n", "sha256:"+hex.EncodeToString(global[:]))
	b.WriteString("\tContracts: map[string]Descriptor{\n")
	for _, c := range contracts {
		hash := contractHash(c)
		fmt.Fprintf(&b, "\t\t%q: {ID: %q, Version: %q, Category: %q, Owner: %q, Authority: Authority(%q), Trust: %q, Sensitivity: %q, Status: %q, Persistence: %s, Fields: %s, Implementation: %s, SchemaHash: %q},\n", c.ID, c.ID, version(c.ID), c.Category, c.Owner, c.Authority, c.Trust, c.Sensitivity, c.Status, stringSlice(c.Persistence), fieldSlice(c.Fields), implementation(c.Implementation), hash)
	}
	b.WriteString("\t},\n\tBoundaries: map[string]BoundaryDescriptor{\n")
	for _, value := range boundaries {
		fmt.Fprintf(&b, "\t\t%q: {ID: %q, InputContracts: %s, OutputContracts: %s, Persistence: %s, Authority: Authority(%q)},\n", value.ID, value.ID, stringSlice(value.InputContracts), stringSlice(value.OutputContracts), stringSlice(value.Persistence), value.Authority)
	}
	b.WriteString("\t},\n\tStores: map[string]StoreDescriptor{\n")
	for _, value := range stores {
		fmt.Fprintf(&b, "\t\t%q: {ID: %q, Authority: Authority(%q), Sensitivity: %q, ContractRefs: %s, Durable: %t, ClearSecretAllowed: %t, ClearBiometricAllowed: %t},\n", value.ID, value.ID, value.Authority, value.Sensitivity, stringSlice(value.ContractRefs), value.Durable, value.ClearSecretAllowed, value.ClearBiometricAllowed)
	}
	b.WriteString("\t},\n\tErrors: map[string]ErrorDescriptor{\n")
	for _, value := range errors {
		fmt.Fprintf(&b, "\t\t%q: {ID: %q, Owner: %q, Category: %q, Retryable: %t, Public: %t, Authority: Authority(%q)},\n", value.ID, value.ID, value.Owner, value.Category, value.Retryable, value.Public, value.Authority)
	}
	b.WriteString("\t},\n\tContractHashes: map[string]string{\n")
	for _, value := range contracts {
		fmt.Fprintf(&b, "\t\t%q: %q,\n", value.ID, contractHash(value))
	}
	b.WriteString("\t},\n}\n")
	return format.Source([]byte(b.String()))
}

func version(id string) string {
	index := strings.LastIndex(id, ".v")
	if index < 0 {
		return ""
	}
	return id[index+1:]
}

func contractHash(value contractcatalog.CatalogContract) string {
	data, _ := json.Marshal(value)
	digest := sha256.Sum256(data)
	return "sha256:" + hex.EncodeToString(digest[:])
}

func stringSlice(values []string) string {
	if len(values) == 0 {
		return "nil"
	}
	copyValues := append([]string(nil), values...)
	sort.Strings(copyValues)
	parts := make([]string, len(copyValues))
	for i, value := range copyValues {
		parts[i] = strconv.Quote(value)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

func fieldSlice(values []contractcatalog.Field) string {
	if len(values) == 0 {
		return "nil"
	}
	copyValues := append([]contractcatalog.Field(nil), values...)
	sort.Slice(copyValues, func(i, j int) bool { return copyValues[i].Name < copyValues[j].Name })
	parts := make([]string, len(copyValues))
	for i, value := range copyValues {
		parts[i] = fmt.Sprintf("{Name: %q, Type: %q, WireName: %q, Required: %t, Nullable: %t, Protection: %q, Sensitivity: %q, Persistence: %s}", value.Name, value.Type, value.WireName, value.Required, value.Nullable, value.Protection, value.Sensitivity, stringSlice(value.Persistence))
	}
	return "[]FieldDescriptor{" + strings.Join(parts, ", ") + "}"
}

func implementation(value contractcatalog.Implementation) string {
	return fmt.Sprintf("ImplementationDescriptor{Kind: %q, Package: %q, Type: %q, WireFormat: %q, Justification: %q}", value.Kind, value.Package, value.Type, value.WireFormat, value.Justification)
}
